name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run project
       run: npm start

      - name: Run tests
        run: npm run test:e2e

      - name: Generate Allure Report
        run: npx allure generate allure-results --clean -o allure-report

      - name: Upload report to Allure TestOps
        env:
          ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
          ALLURE_ENDPOINT: "https://hardy.testops.cloud/"
          ALLURE_PROJECT_ID: "#1"
        run: allurectl upload --results allure-results