name: Run tests

on:
  push:
  workflow_dispatch:
    inputs:
      ALLURE_JOB_RUN_ID:
        description: ALLURE_JOB_RUN_ID service parameter. Leave blank.
      ALLURE_USERNAME:
        description: ALLURE_USERNAME service parameter. Leave blank.

env:
  ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
  ALLURE_ENDPOINT: https://hardy.testops.cloud/
  ALLURE_PROJECT_ID: 1
  ALLURE_RESULTS: allure

jobs:
  all-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Start Angular server
        run: npm start &

      - name: Wait for Angular to be ready
        run: npx wait-on http://localhost:4200

      - name: Run Angular e2e tests
        run: npm run test:e2e

      - name: Install allurectl manually
        run: |
          wget https://github.com/allure-framework/allurectl/releases/latest/download/allurectl_linux_amd64 -O allurectl
          chmod +x allurectl
          sudo mv allurectl /usr/local/bin/

      - name: Verification allurectl
        run: allurectl --version

      - name: Upload report to Allure TestOps
        env:
          ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
          ALLURE_ENDPOINT: ${{ env.ALLURE_ENDPOINT }}
          ALLURE_PROJECT_ID: ${{ env.ALLURE_PROJECT_ID }}
        run: allurectl upload allure

